// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progetto_Web_2_IoT_Auth.Data;

#nullable disable

namespace Progetto_Web_2_IoT_Auth.Migrations
{
    [DbContext(typeof(DbContextSQLite))]
    [Migration("20260304195030_InitialNewSchema")]
    partial class InitialNewSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.HasIndex("UserId", "ZoneId")
                        .IsUnique();

                    b.ToTable("access", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = "admin",
                            UserId = 1,
                            ZoneId = 1
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Mail = "admin@example.local",
                            PasswordHash = "$2a$11$wBHBpKnudJZ9U1yNZT5l5u4xGkVmI0QRjvEm0ZQ76C8/3Ha7jKOaC",
                            Role = "admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Automation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("automation", (string)null);
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("St")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("device", (string)null);
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("zone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "default",
                            Type = "default"
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Access", b =>
                {
                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.AppUser", "User")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.Zone", "Zone")
                        .WithMany("Accesses")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Automation", b =>
                {
                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.Device", "Device")
                        .WithMany("Automations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Device", b =>
                {
                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.Zone", "Zone")
                        .WithMany("Devices")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.AppUser", b =>
                {
                    b.Navigation("Accesses");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Device", b =>
                {
                    b.Navigation("Automations");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Zone", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
