// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Progetto_Web_2_IoT_Auth.Data;

#nullable disable

namespace Progetto_Web_2_IoT_Auth.Migrations
{
    [DbContext(typeof(DbContextSQLite))]
    partial class DbContextSQLiteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Access", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.HasIndex("UserId", "ZoneId")
                        .IsUnique();

                    b.ToTable("access", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessLevel = "operator",
                            UserId = 2,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 2,
                            AccessLevel = "operator",
                            UserId = 2,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 3,
                            AccessLevel = "view",
                            UserId = 3,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 4,
                            AccessLevel = "view",
                            UserId = 4,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 5,
                            AccessLevel = "view",
                            UserId = 4,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 6,
                            AccessLevel = "view",
                            UserId = 4,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 7,
                            AccessLevel = "view",
                            UserId = 4,
                            ZoneId = 5
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("app_setting", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "WeatherCity",
                            Value = "Roma"
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DarkMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mail")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DarkMode = false,
                            Mail = "admin@example.local",
                            PasswordHash = "$2a$11$5bXqGaqh3uehFVuTEdfWLOfFUxE7KFIRYv/XOqmEgdon7oNxpVQxS",
                            Role = "admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            DarkMode = false,
                            Mail = "alice@example.local",
                            PasswordHash = "$2a$12$vXc041cxsHJ7zMmuMHxjl.JpanScQdMOicmmzD74UErojYRCcHaoi",
                            Role = "user",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 3,
                            DarkMode = true,
                            Mail = "bob@example.local",
                            PasswordHash = "$2a$12$vXc041cxsHJ7zMmuMHxjl.JpanScQdMOicmmzD74UErojYRCcHaoi",
                            Role = "user",
                            Username = "bob"
                        },
                        new
                        {
                            Id = 4,
                            DarkMode = false,
                            Mail = "charlie@example.local",
                            PasswordHash = "$2a$12$vXc041cxsHJ7zMmuMHxjl.JpanScQdMOicmmzD74UErojYRCcHaoi",
                            Role = "user",
                            Username = "charlie"
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Automation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TimeCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WeatherCondition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.ToTable("automation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceId = 1,
                            Level = 100,
                            Power = true,
                            TimeCondition = "18:00",
                            WeatherCondition = "any"
                        },
                        new
                        {
                            Id = 2,
                            DeviceId = 1,
                            Level = 0,
                            Power = false,
                            TimeCondition = "23:00",
                            WeatherCondition = "any"
                        },
                        new
                        {
                            Id = 3,
                            DeviceId = 3,
                            Level = 80,
                            Power = true,
                            TimeCondition = "07:00",
                            WeatherCondition = "sunny"
                        },
                        new
                        {
                            Id = 4,
                            DeviceId = 3,
                            Level = 0,
                            Power = false,
                            TimeCondition = "09:00",
                            WeatherCondition = "any"
                        },
                        new
                        {
                            Id = 5,
                            DeviceId = 6,
                            Level = 20,
                            Power = true,
                            TimeCondition = "22:00",
                            WeatherCondition = "cold"
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeviceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IpAddress")
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Power")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DeviceTypeId");

                    b.HasIndex("ZoneId");

                    b.ToTable("device", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeviceTypeId = 1,
                            IpAddress = "192.168.1.10",
                            Level = 80,
                            Name = "Main Light",
                            Power = true,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 2,
                            DeviceTypeId = 1,
                            IpAddress = "192.168.1.11",
                            Level = 40,
                            Name = "TV Backlight",
                            Power = false,
                            ZoneId = 2
                        },
                        new
                        {
                            Id = 3,
                            DeviceTypeId = 2,
                            IpAddress = "192.168.1.20",
                            Level = 0,
                            Name = "Garden Sprinkler",
                            Power = false,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 4,
                            DeviceTypeId = 2,
                            IpAddress = "192.168.1.21",
                            Level = 0,
                            Name = "Lawn Sprinkler",
                            Power = false,
                            ZoneId = 3
                        },
                        new
                        {
                            Id = 5,
                            DeviceTypeId = 1,
                            IpAddress = "192.168.1.30",
                            Level = 60,
                            Name = "Bedroom Light",
                            Power = false,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 6,
                            DeviceTypeId = 3,
                            IpAddress = "192.168.1.31",
                            Level = 21,
                            Name = "Thermostat",
                            Power = true,
                            ZoneId = 4
                        },
                        new
                        {
                            Id = 7,
                            DeviceTypeId = 1,
                            IpAddress = "192.168.1.40",
                            Level = 100,
                            Name = "Garage Light",
                            Power = false,
                            ZoneId = 5
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.DeviceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("device_type", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "light"
                        },
                        new
                        {
                            Id = 2,
                            Name = "sprinkler"
                        },
                        new
                        {
                            Id = 3,
                            Name = "thermostat"
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("zone", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "default",
                            Type = "default"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Living Room",
                            Type = "indoor"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Garden",
                            Type = "outdoor"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bedroom",
                            Type = "indoor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Garage",
                            Type = "outdoor"
                        });
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Access", b =>
                {
                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.AppUser", "User")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.Zone", "Zone")
                        .WithMany("Accesses")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Automation", b =>
                {
                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.Device", "Device")
                        .WithMany("Automations")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Device", b =>
                {
                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.DeviceType", "DeviceType")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Progetto_Web_2_IoT_Auth.Data.Model.Zone", "Zone")
                        .WithMany("Devices")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeviceType");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.AppUser", b =>
                {
                    b.Navigation("Accesses");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Device", b =>
                {
                    b.Navigation("Automations");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.DeviceType", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Progetto_Web_2_IoT_Auth.Data.Model.Zone", b =>
                {
                    b.Navigation("Accesses");

                    b.Navigation("Devices");
                });
#pragma warning restore 612, 618
        }
    }
}
